### ISSUE TITLE
rotating the key

### ISSUE THREAD

**Issue by laimison** [ankane/ip_anonymizer#1]
First of all thanks for your great gem. Do you have a mechanism to rotate the secret key? I believe this will help to ensure that real IPs are not restored via hashed IPv4 rainbow table which is I guess roughly close or more than 1TB of hashes in size.

**Comment by ankane** [comment]
Hey @laimison, not sure I fully understand the question. You can pass a new key to rotate it.

**Comment by laimison** [comment]
I thought maybe there is a solution to avoid mentioned issue. I meant if you go through all four billion IPv4 addresses and hash one by one, write IP and hash to file then in theory they are reversible. Correct me if I'm wrong or didn't understand this tool please. In case you think this should be solved using an additional tool on top of it, then please close the case. I would be able to connect ip_anonymizer with an additional tool. Thanks

**Comment by ankane** [comment]
If an attacker gets access to the key (or is able to hash any IP and see the result), they can build a rainbow table, which will expose the original IPs (collisions aside). You can generate a new key on a regular interval (say once a week) and throw out the old key afterwards so a successful attacker will only be able to do this on the most recent data. The key is just input to the library, so you can do this already.

**Comment by ankane** [comment]
Cleaning up issues
